#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repository_root="$(cd "$script_dir/.." && pwd)"
project_prefix="neventstore-sql"
maximum_environment_name_length=48

normalize_environment_name() {
  local value="$1"
  local normalized

  normalized="$(printf '%s' "$value" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//')"

  if [[ -z "$normalized" ]]; then
    echo "Environment name '$value' does not contain any supported characters." >&2
    return 1
  fi

  normalized="${normalized:0:$maximum_environment_name_length}"
  printf '%s' "${normalized%-}"
}

get_assigned_port() {
  local service="$1"
  local container_port="$2"
  local endpoint
  local port

  endpoint="$("${compose_command[@]}" port "$service" "$container_port" | tail -n 1)"
  port="${endpoint##*:}"

  if [[ ! "$port" =~ ^[0-9]+$ ]]; then
    echo "Unable to determine the host port for $service:$container_port from '$endpoint'." >&2
    return 1
  fi

  printf '%s' "$port"
}

if [[ $# -gt 1 ]]; then
  echo "Only one environment name may be provided." >&2
  exit 2
fi

raw_environment_name="${1:-$(basename "$repository_root")}"
environment_name="$(normalize_environment_name "$raw_environment_name")"

case "$environment_name" in
  debug|test|ci)
    port_mode="$environment_name"
    ;;
  *)
    port_mode="dynamic"
    ;;
esac

project_name="$project_prefix-$environment_name"
base_compose_file="$script_dir/docker-compose.yml"
override_compose_file="$script_dir/docker-compose.$port_mode.yml"
env_file="$repository_root/.env"

if ! docker compose version >/dev/null 2>&1; then
  echo "Docker Compose v2 is required. Ensure 'docker compose' is available." >&2
  exit 1
fi

compose_command=(
  docker compose
  --project-name "$project_name"
  --file "$base_compose_file"
  --file "$override_compose_file"
)

echo "Starting '$project_name' using $port_mode ports..."
"${compose_command[@]}" up --detach --wait

database_password="$("${compose_command[@]}" exec -T sqlexpress printenv MSSQL_SA_PASSWORD | tr -d '\r')"

"${compose_command[@]}" exec -T sqlexpress \
  /opt/mssql-tools/bin/sqlcmd \
  -S localhost \
  -U sa \
  -P "$database_password" \
  -Q "IF DB_ID(N'NEventStore') IS NULL CREATE DATABASE [NEventStore];"

sqlserver_port="$(get_assigned_port sqlexpress 1433)"
mysql_port="$(get_assigned_port mysql 3306)"
postgres_port="$(get_assigned_port postgres 5432)"
oracle_port="$(get_assigned_port oracle 1521)"

temporary_env_file="$env_file.tmp"
cat > "$temporary_env_file" <<EOF_ENV
# Generated by docker/start-environment.sh for environment '$environment_name'.
NEventStore.MsSql=Server=127.0.0.1,$sqlserver_port;Database=NEventStore;User Id=sa;Password=$database_password;TrustServerCertificate=True;
NEventStore.MySql=Server=127.0.0.1;Port=$mysql_port;Database=NEventStore;Uid=sa;Pwd=$database_password;AutoEnlist=false;
NEventStore.PostgreSql=Server=127.0.0.1;Port=$postgres_port;Database=NEventStore;Uid=sa;Pwd=$database_password;Enlist=false;
NEventStore.Oracle=Data Source=127.0.0.1:$oracle_port/XE;User Id=system;Password=$database_password;Persist Security Info=True;
EOF_ENV
mv "$temporary_env_file" "$env_file"

echo
echo "Environment: $environment_name"
echo "Compose project: $project_name"
echo "Connection strings written to: $env_file"
