<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;$(ModernTargetFrameworks)</TargetFrameworks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>NEventStore.Persistence.Sql.Tests</AssemblyName>
    <RootNamespace>NEventStore.Persistence.Sql.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="PersistenceTests.Transactions.Async.cs" />
    <Compile Remove="PersistenceTests.Transactions.cs" />
    <Compile Remove="PersistenceTests.Snapshots.Async.cs" />
    <Compile Remove="PersistenceTests.Snapshots.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="packages.config" />
  </ItemGroup>

  <ItemGroup>
    <None Include="PersistenceTests.Transactions.Async.cs" />
    <None Include="PersistenceTests.Transactions.cs" />
    <None Include="PersistenceTests.Snapshots.Async.cs" />
    <None Include="PersistenceTests.Snapshots.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\dependencies\NEventStore\src\NEventStore\NEventStore.Core.csproj" />
    <ProjectReference Include="..\NEventStore.Persistence.Sql\NEventStore.Persistence.Sql.Core.csproj" />
  </ItemGroup>

</Project>
